---
- include: vulnerable.yml                                tags=security,vulnerable
- include: kernel.yml                                    tags=security,kernel
- include: ../../../../tasks/linux/reboot_required.yml   tags=security
- include: apt.yml                                       tags=security,apt
