---
- name: Vulnerable | Bash shellshock | Check if vulnerable
  sudo: false
  shell: curl -s https://shellshocker.net/shellshock_test.sh | bash
  ignore_errors: true
  register: bash_shellshock_vulnerable
  changed_when: false

- action: mail
    subject="Bash is potentially vulnerable on {{ ansible_hostname }}"
    body="{{ bash_shellshock_vulnerable.stdout }}"
    from="Ansible <admin@the-rebellion.net>"
    to="Ash McKenzie <ash@the-rebellion.net"
  when: "bash_shellshock_vulnerable.rc != 0"

- name: Vulnerable | Bash shellshock | Apply security update if we are vulnerable
  apt: name=bash state=latest
  when: "bash_shellshock_vulnerable.rc != 0"

- name: Vulnerable | Bash shellshock | Double check if vulnerable
  shell: curl -s https://shellshocker.net/shellshock_test.sh | bash > /dev/null 2>&1
  when: "bash_shellshock_vulnerable.rc != 0"
  ignore_errors: true
  register: bash_shellshock_vulnerable
  changed_when: "bash_shellshock_vulnerable.rc != 0"
  failed_when: "bash_shellshock_vulnerable.rc != 0"
