---
- hosts: linux
  sudo: true
  roles:
    - common
    - ../roles/linux/common
    - ../roles/linux/maintenance
  tasks:
    - include: tasks/linux/packages_updates_available.yml
    - include: tasks/linux/reboot_required.yml
