---
- hosts: Linux
  sudo: true
  roles:
    - ../roles/Linux/maintenance
  tasks:
    - include: tasks/Linux/packages_updates_available.yml
    - include: tasks/Linux/reboot_required.yml

- hosts: Darwin
  sudo: true
  roles:
    - ../roles/Darwin/maintenance
  tasks:
    - include: tasks/Darwin/packages_updates_available.yml

