---
- hosts: all
  sudo: true
  roles:
    - common
  tasks:
    - include: tasks/smtp.yml
    - include: tasks/packages.yml
    - include: tasks/ansible_pull.yml
  handlers:
    - include: handlers/smtp.yml

- hosts: Ubuntu
  sudo: true
  roles:
    - common
  tasks:
    - include: tasks/languages.yml
