---
- hosts: all
  sudo: true
  vars_files:
    - "vars/default.yml"
    - "vars/{{ ansible_distribution }}.yml"
    - "vars/{{ ansible_distribution }}/{{ ansible_distribution_version }}.yml"
    - "vars/{{ ansible_distribution }}/{{ ansible_distribution_version }}_{{ ansible_architecture }}.yml"
    - "vars/{{ ansible_distribution }}/{{ ansible_distribution_version }}_{{ ansible_virtualization_type }}.yml"
  tasks:
    - include: tasks/smtp.yml
    - include: tasks/packages.yml
    - include: tasks/ansible_pull.yml
  handlers:
    - include: handlers/smtp.yml

- hosts: Ubuntu
  sudo: true
  vars_files:
    - "vars/default.yml"
    - "vars/{{ ansible_distribution }}.yml"
    - "vars/{{ ansible_distribution }}/{{ ansible_distribution_version }}.yml"
    - "vars/{{ ansible_distribution }}/{{ ansible_distribution_version }}_{{ ansible_architecture }}.yml"
    - "vars/{{ ansible_distribution }}/{{ ansible_distribution_version }}_{{ ansible_virtualization_type }}.yml"
  tasks:
    - include: tasks/languages.yml
