---
- hosts: Linux
  sudo: true
  roles:
    - ../roles/Linux/base

- hosts: Web
  sudo: true
  roles:
    - ../roles/Linux/web
    - ../roles/Linux/rails

- hosts: Darwin
  sudo: true
  roles:
    - ../roles/Darwin/base
