---
- hosts: linux
  sudo: true
  roles:
    - ../roles/linux/base

- hosts: linux
  sudo: true
  roles:
    - ../roles/linux/web
    - ../roles/linux/rails

- hosts: mac
  sudo: true
  roles:
    - ../roles/mac/base
