---
- hosts: all
  sudo: true
  roles:
    - common
    - base
  tasks:
    - include: tasks/ruby.yml  tags=ruby
      when: "ansible_distribution == 'Ubuntu'"

- hosts: web
  sudo: true
  roles:
    - web
