---
- hosts: Linux
  sudo: true
  roles:
    - common
    - ../roles/linux/common
  tasks:
    - include: tasks/linux/packages_upgrade_all.yml

- hosts: Darwin
  sudo: false
  roles:
    - common
    - ../roles/mac/common
  tasks:
    - include: tasks/mac/packages_upgrade_all.yml
