---
- hosts: Linux
  sudo: true
  roles:
    - common
    - ../roles/Linux/common
  tasks:
    - include: tasks/Linux/packages_updates_available.yml

- hosts: Darwin
  sudo: true
  roles:
    - common
    - ../roles/Darwin/common
  tasks:
    - include: tasks/Darwin/packages_updates_available.yml
