---
- hosts: linux
  sudo: true
  roles:
    - common
  tasks:
    - include: tasks/linux/packages_updates_available.yml

- hosts: mac
  sudo: true
  roles:
    - common
  tasks:
    - include: tasks/mac/packages_updates_available.yml
