---
- hosts: Linux
  sudo: true
  roles:
    - common
    - ../roles/linux/common
  tasks:
    - include: tasks/linux/packages_updates_available.yml

- hosts: Darwin
  sudo: true
  roles:
    - common
    - ../roles/mac/common
  tasks:
    - include: tasks/mac/packages_updates_available.yml
