---
- hosts: linux
  sudo: true
  roles:
    - common
    - ../roles/linux/common
  tasks:
    - include: tasks/linux/packages_updates_available.yml

- hosts: mac
  sudo: true
  roles:
  - common
    - ../roles/mac/common
  tasks:
    - include: tasks/mac/packages_updates_available.yml
