---
- name: Ruby | Brightbox Ruby APT repo
  apt_repository: repo='ppa:brightbox/ruby-ng-experimental'

- name: Ruby | Install Ruby
  apt: name="{{ item }}={{ ruby.version }}" state=present
  with_items:
    - "ruby{{ ruby.base_version }}"
    - "ruby{{ ruby.base_version }}-dev"

- name: Ruby | Set alternative
  alternatives: name=ruby path="/usr/bin/ruby{{ ruby.base_version }}"

- name: Ruby | Set alternative
  alternatives: name=gem path="/usr/bin/gem{{ ruby.base_version }}"

- shell: gem list -i bundler --version {{ ruby.bundler_version }}
  ignore_errors: true
  changed_when: false
  register: bundler_installed

- name: Ruby | Install Bundler
  shell: gem install bundler -v={{ ruby.bundler_version }}
  when: "bundler_installed.rc != 0"
