- stat: path=/usr/local/go1.3.3
  ignore_errors: true
  changed_when: false
  register: go_installed

- name: Golang | Download
  get_url: url=http://dave.cheney.net/paste/go.1.3.3.linux-arm~multiarch-armv6-1.tar.gz dest=/tmp/go.1.3.3.linux-arm~multiarch-armv6-1.tar.gz
  when: go_installed.stat.exists == false

- name: Golang | Install
  shell: cd /tmp ; rm -rf go ; tar xzf go.1.3.3.linux-arm~multiarch-armv6-1.tar.gz ; mv go /usr/local/go1.3.3 ; ln -nfs /usr/local/go1.3.3 /usr/local/go
  when: go_installed.stat.exists == false
