---
- name: Security | Setup unattended upgrades
  template: src=templates/security/unattended_upgrades.j2 dest=/etc/apt/apt.conf.d/50unattended-upgrades owner=root group=root mode=0644

- name: Security | Bash shellshock | Check if vulnerable
  shell: curl -s https://shellshocker.net/shellshock_test.sh | bash > /dev/null 2>&1
  ignore_errors: true
  register: bash_shellshock_vulnerable

- name: Security | Bash shellshock | Update apt index
  apt: update_cache=true cache_valid_time=3600
  when: "bash_shellshock_vulnerable.rc != 0"

- name: Security | Bash shellshock | Apply security update if we are vulnerable
  apt: name=bash state=latest update_cache=true
  when: "bash_shellshock_vulnerable.rc != 0"

- name: Security | Bash shellshock | Double check if vulnerable
  shell: curl -s https://shellshocker.net/shellshock_test.sh | bash > /dev/null 2>&1
  ignore_errors: true
  register: bash_shellshock_vulnerable
  failed_when: "bash_shellshock_vulnerable.rc != 0"
