---
- name: Updates | Look for homebrew updates
  command: "{{ homebrew.path }}/brew outdated"
  register: packages
  changed_when: false

- name: Updates | homebrew updates (if available)
  debug: var=packages.stdout_lines
  changed_when: "packages.stdout_lines.__len__() > 0"

- name: Updates | Email homebrew updates (if available)
  script: ../../scripts/darwin_sendmail.sh \"Updates available for {{ ansible_hostname }}\" \"{{ packages.stdout }}\"
  when: "packages.stdout_lines.__len__() > 0"

- name: Updates | Look for MacOS X updates
  command: /usr/sbin/softwareupdate -l
  register: updates
  changed_when: false

- name: Updates | MacOS X updates (if available)
  debug: var=updates.stdout_lines
  when: "'No new software available' not in updates.stdout"

- name: Updates | Email MacOS X updates (if available)
  script: ../../scripts/darwin_sendmail.sh \"Updates available for {{ ansible_hostname }}\" \"{{ updates.stdout }}\"
  when: "'No new software available' not in updates.stdout"
