---
locale: en_AU.UTF-8
timezone: Australia/Melbourne
packages_to_install: []
packages_to_remove: []
additional_packages_to_install: []
ansible_pull:
  cron_user: root
  critical_schedule: '*/5 * * * *'
  critical_tags: critical
  non_critical_schedule: '*/18 * * * *'
  non_critical_tags: non_critical
  daily_schedule: '32 6 * * *'
  daily_tags: daily
  logfile: /var/log/ansible-pull.log
  workdir: /var/lib/ansible/local
  repo_url: https://github.com/ashmckenzie/ansible-play.git
