---
- name: Ansible pull | Update apt index
  apt: update_cache=true cache_valid_time=3600

- name: Ansible pull | Install ansible
  action: apt pkg=ansible state=installed

- name: Ansible pull | Create local directory to work from
  action: file path={{workdir}} state=directory owner=root group=root mode=0751

- name: Ansible pull | Create crontab entry to clone/pull git repository
  action: template src=templates/ansible_pull/cron.j2 dest=/etc/cron.d/ansible-pull owner=root group=root mode=0644

- name: Ansible pull | Create logrotate entry for ansible-pull.log
  action: template src=templates/ansible_pull/logrotate.j2 dest=/etc/logrotate.d/ansible-pull owner=root group=root mode=0644
