---
- name: Ansible | Install Python and dev
  apt: name={{ item }} state=present
  with_items:
    - python
    - python-dev

- stat: path=/usr/local/bin/pip
  register: pip_installed
  changed_when: false

- name: Ansible | Install pip
  shell: curl https://bootstrap.pypa.io/get-pip.py | python -
  when: pip_installed.stat.exists == false

- name: Ansible | Install ansible
  pip: name=ansible version=1.7.2 state=present

- name: Ansible | Create /etc/ansible
  file: path=/etc/ansible state=directory

- name: Ansible | Create /etc/ansible/hosts
  template: src=ansible/hosts.j2 dest=/etc/ansible/hosts owner=root group=root mode=0644

- name: Ansible | Create work directory
  file: path={{ ansible_pull.workdir }}/{{ item }} state=directory owner=root group=root mode=0751
  with_items:
    - critical
    - non_critical
    - daily

- name: Ansible | Create crontab
  template: src=ansible/cron.j2 dest=/etc/cron.d/ansible-pull owner=root group=root mode=0644

- name: Ansible | Create logrotate config
  template: src=ansible/logrotate.j2 dest=/etc/logrotate.d/ansible-pull owner=root group=root mode=0644
